Badminton/Controllers/tb_BrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Badminton.Models;

namespace Badminton.Controllers
{
    public class tb_BrandController : Controller
    {
        private BadmintonContext db = new BadmintonContext();

        // GET: tb_Brand
        public ActionResult Index()
        {
            return View(db.tb_Brand.ToList());
        }

        // GET: tb_Brand/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Brand tb_Brand = db.tb_Brand.Find(id);
            if (tb_Brand == null)
            {
                return HttpNotFound();
            }
            return View(tb_Brand);
        }

        // GET: tb_Brand/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tb_Brand/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,brandname,logo")] tb_Brand tb_Brand)
        {
            if (ModelState.IsValid)
            {
                db.tb_Brand.Add(tb_Brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tb_Brand);
        }

        // GET: tb_Brand/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Brand tb_Brand = db.tb_Brand.Find(id);
            if (tb_Brand == null)
            {
                return HttpNotFound();
            }
            return View(tb_Brand);
        }

        // POST: tb_Brand/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,brandname,logo")] tb_Brand tb_Brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_Brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tb_Brand);
        }

        // GET: tb_Brand/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Brand tb_Brand = db.tb_Brand.Find(id);
            if (tb_Brand == null)
            {
                return HttpNotFound();
            }
            return View(tb_Brand);
        }

        // POST: tb_Brand/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tb_Brand tb_Brand = db.tb_Brand.Find(id);
            db.tb_Brand.Remove(tb_Brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Badminton/Controllers/tb_OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Badminton.Models;

namespace Badminton.Controllers
{
    public class tb_OrderController : Controller
    {
        private BadmintonContext db = new BadmintonContext();

        //Xem danh sách đơn hàng

        public ActionResult ShowListOrder(int? id)
        {
            var list = db.tb_Order.Where(p => p.userid == id).ToList();
            return View(list);
        }

        // GET: tb_Order
        public ActionResult Index()
        {
            var tb_Order = db.tb_Order.Include(t => t.tb_User);
            return View(tb_Order.ToList());
        }

        // GET: tb_Order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Order tb_Order = db.tb_Order.Find(id);
            if (tb_Order == null)
            {
                return HttpNotFound();
            }
            return View(tb_Order);
        }

        // GET: tb_Order/Create
        public ActionResult Create()
        {
            ViewBag.userid = new SelectList(db.tb_User, "id", "fullname");
            return View();
        }

        // POST: tb_Order/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,fullname,sdt,addr,note,orderdate,stt,userid")] tb_Order tb_Order)
        {
            if (ModelState.IsValid)
            {
                db.tb_Order.Add(tb_Order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.userid = new SelectList(db.tb_User, "id", "fullname", tb_Order.userid);
            return View(tb_Order);
        }

        // GET: tb_Order/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Order tb_Order = db.tb_Order.Find(id);
            if (tb_Order == null)
            {
                return HttpNotFound();
            }
            ViewBag.userid = new SelectList(db.tb_User, "id", "fullname", tb_Order.userid);
            return View(tb_Order);
        }

        // POST: tb_Order/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,fullname,sdt,addr,note,orderdate,stt,userid")] tb_Order tb_Order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_Order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.userid = new SelectList(db.tb_User, "id", "fullname", tb_Order.userid);
            return View(tb_Order);
        }

        // GET: tb_Order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Order tb_Order = db.tb_Order.Find(id);
            if (tb_Order == null)
            {
                return HttpNotFound();
            }
            return View(tb_Order);
        }

        // POST: tb_Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tb_Order tb_Order = db.tb_Order.Find(id);
            db.tb_Order.Remove(tb_Order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Badminton/Controllers/tb_UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using Badminton.Models;

namespace Badminton.Controllers
{
    public class tb_UserController : Controller
    {
        private BadmintonContext db = new BadmintonContext();

        //DELETE CART
        public ActionResult DeleteCart(int id)
        {
            List<ProductSelected> list = (List<ProductSelected>)Session["cart"];

            ProductSelected productDelete = list.FirstOrDefault(p => p.id == id);
            list.Remove(productDelete);
            Session["cart"] = list;
            return View("Cart");
        }

        //Buy 
        public ActionResult Buy()
        {
            return View();
        }

        //GET: Cart

        public ActionResult Cart()
        {
            return View();
        }

        //GET: Confirm
        public ActionResult Confirm(FormCollection form)
        {
            ProductSelected product = new ProductSelected();

            if ((form["productid"]) == null)
            {
                return View();
            } else
            {
                int productID = int.Parse(form["productid"]);
                string productName = form["productname"];
                int quantity = int.Parse(form["productquantity"]);
                float price = float.Parse(form["productprice"]);
                string size = form["productsize"];
                string image = form["productimage"];

                product.productID = productID;
                product.productName = productName;
                product.productSize = size;
                product.productPrice = price;
                product.productQuantity = quantity;
                product.productImage = image;

                List<ProductSelected> listProduct = new List<ProductSelected>();
                if (Session["cart"] != null)
                {
                    listProduct = (List<ProductSelected>)Session["cart"];
                }
                if (listProduct.Contains(product))
                {
                    int index = listProduct.IndexOf(product);
                    listProduct[index].productQuantity+=quantity;
                }
                else
                {
                    int id = listProduct.Count;
                    product.id = id + 1;
                    listProduct.Add(product);
                }
                Session["cart"] = listProduct;
                return View();
            }
            
        }

        // GET: tb_User
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult XLogin(string username, string password)
        {
            var query = db.tb_User.SingleOrDefault(p => p.username == username && p.passwd == password);
            if (query == null)
            {
                ViewBag.msg = "Tài khoản không tồn tại";
                return View("Login");
            }

            Session["account"] = query.id;
            Session["UserName"] = query.fullname;

            if (query.role_id == 1)
            {
                return Redirect("/tb_Product/Index");
            }
            return Redirect("/Home/Index");
        }
        public ActionResult Logout()
        {
            Session.Remove("account");
            Session.Remove("UserName");
            return Redirect("/Home/Index");
        }
        public ActionResult Regis()
        {
            return View();
        }
        public ActionResult Regising(string name, string email, string phone_number, string password, string repassword)
        {
            if (password != repassword)
            {
                ViewBag.msg = "Mật khẩu không khớp!";
                return View("Regis");
            }
            try
            {
                tb_User newUser = new tb_User();
                newUser.fullname = name;
                newUser.username = email;
                newUser.phonenumber = phone_number;
                newUser.passwd = password;
                newUser.role_id = 2;

                db.tb_User.Add(newUser);
                db.SaveChanges();
                return Redirect("/Home/Index");
            }
            catch (Exception)
            {
                ViewBag.msg = "Email đã tồn tại!";
                return View("Regis");
            }
            
        }
        public ActionResult Index()
        {
            var tb_User = db.tb_User.Include(t => t.tb_Role);
            return View(tb_User.ToList());
        }

        // GET: tb_User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_User tb_User = db.tb_User.Find(id);
            if (tb_User == null)
            {
                return HttpNotFound();
            }
            return View(tb_User);
        }

        // GET: tb_User/Create
        public ActionResult Create()
        {
            ViewBag.role_id = new SelectList(db.tb_Role, "id", "rolename");
            return View();
        }

        // POST: tb_User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,fullname,username,phonenumber,addr,passwd,role_id")] tb_User tb_User)
        {
            if (ModelState.IsValid)
            {
                db.tb_User.Add(tb_User);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.role_id = new SelectList(db.tb_Role, "id", "rolename", tb_User.role_id);
            return View(tb_User);
        }

        // GET: tb_User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_User tb_User = db.tb_User.Find(id);
            if (tb_User == null)
            {
                return HttpNotFound();
            }
            ViewBag.role_id = new SelectList(db.tb_Role, "id", "rolename", tb_User.role_id);
            return View(tb_User);
        }

        // POST: tb_User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,fullname,username,phonenumber,addr,passwd,role_id")] tb_User tb_User)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_User).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.role_id = new SelectList(db.tb_Role, "id", "rolename", tb_User.role_id);
            return View(tb_User);
        }

        // GET: tb_User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_User tb_User = db.tb_User.Find(id);
            if (tb_User == null)
            {
                return HttpNotFound();
            }
            return View(tb_User);
        }

        // POST: tb_User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tb_User tb_User = db.tb_User.Find(id);
            db.tb_User.Remove(tb_User);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Badminton/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LDSHOP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .menu {
            background-color: #EEEEEE !important;
            color: black;
        }
        
       .body-content {
           min-height: 1000px;
       }
        .footer {
            background-color: #EEEEEE;
            color: black;
            padding: 20px;
        }
        .nav-link {
            color: black;
        }
        .nav-link:hover {
            color: blue;
        }
        a {
            text-decoration: none;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark menu">
        <div class="container">
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Quản lý người dùng", "Index", "tb_User", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Quản lý thương hiệu", "Index", "tb_Brand", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Quản lý danh mục", "Index", "tb_Category", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Quản lý sản phẩm", "Index", "tb_Product", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Quản lý đơn hàng", "Index", "tb_Order", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Quản lý chi tiết đơn hàng", "Index", "tb_OrderDetail", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Đăng xuất", "Logout", "tb_User", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()

    </div>
    <footer style="margin-top: 20px;">
        <div class="text-center footer container-fluid">
            <p>CÔNG TY TNHH LINDAN BADMINTON</p>
            <p>SĐT: 0967983709</p>
            <p>EMAIL: nguyenmanhcuong02062002@gmail.com</p>
            <p>Địa chỉ: phố Văn Trì, Minh Khai, Bắc Từ Liêm, Hà Nội</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Badminton/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .menu {
            background-color: #E95211 !important;
        }
        .nav-link, .navbar-brand {
            color: white;
        }
        .acc {
            justify-content: flex-end;
        }
        .footer {
            background-color: #E95211;
            color: white;
            padding: 20px;
        }
        .body-content{
            min-height: 1000px;
        }        
        .submenu {
            position: relative;
        }
        .sub-menu {
            display: none;
            position: absolute;
            border: 1px solid #EEEEEE;
            background-color: white;
            width:max-content;
            z-index: 1000;
        }
        .submenu:hover .sub-menu {
            display: flex;
            flex-direction: column;
           
        }
        .sub-menu li a {
            color: #E95211;
            padding: 10px;
        }
        .sub-menu li a:hover {
            color: black;
        }
        .sub-menu li {
            border-bottom: 1px solid silver;
        }

        
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm menu">
        <div class="container">
            @Html.ActionLink("LDSHOP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand fw-bold" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="submenu">
                        @Html.ActionLink("SẢN PHẨM", "ShowAllProduct", "tb_Product" , new { area = ""}, new { @class = "nav-link fw-bold"})
                        <ul class="sub-menu navbar-nav">
                            @{ Html.RenderAction("SubMenu", "Home");}   
                        </ul>
                    </li>
                    <li>@Html.ActionLink("GIỚI THIỆU", "About", "Home", new { area = "" }, new { @class = "nav-link fw-bold" })</li>
                    <li>@Html.ActionLink("LIÊN HỆ", "Contact", "Home", new { area = "" }, new { @class = "nav-link fw-bold" })</li>
                </ul>
            </div>

            <form class="d-flex timkiem" role="search" action="/tb_Product/Search" method="post">
                <input class="form-control me-2" type="search" placeholder="Tìm kiếm sản phẩm..." aria-label="Search" name="searchString">
                <button class="btn btn-success" type="submit">Search</button>
            </form>
            @{
                if (Session["account"] == null)
                {
                    <div class="collapse navbar-collapse d-sm-inline-flex acc">
                        <ul class="navbar-nav flex-grow">
                            <li>@Html.ActionLink("Giỏ hàng", "Cart", "tb_User", new { area = "" }, new { @class = "nav-link fw-bold" })</li>
                            <li>@Html.ActionLink("Đăng nhập", "Login", "tb_User", new { area = "" }, new { @class = "nav-link fw-bold" })</li>
                            <li>@Html.ActionLink("Đăng ký", "Regis", "tb_User", new { area = "" }, new { @class = "nav-link fw-bold" })</li>
                        </ul>
                    </div>
                }
                else
                {
                    <div class="collapse navbar-collapse d-sm-inline-flex acc">
                        <ul class="navbar-nav flex-grow">
                            <li><a href="/tb_Order/ShowListOrder/@Session["account"]" class="nav-link fw-bold">Đơn hàng</a></li>
                            <li>@Html.ActionLink("Giỏ hàng", "Cart", "tb_User", new { area = "" }, new { @class = "nav-link fw-bold" })</li>
                            <li>@Html.ActionLink("Đăng xuất", "Logout", "tb_User", new { area = "" }, new { @class = "nav-link fw-bold" })</li>
                        </ul>
                    </div>
                }
            }

        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()

    </div>
    <footer style="margin-top: 20px;">
        <div class="text-center footer container-fluid">
            <p>CÔNG TY TNHH LINDAN BADMINTON</p>
            <p>SĐT: 0967983709</p>
            <p>EMAIL: nguyenmanhcuong02062002@gmail.com</p>
            <p>Địa chỉ: phố Văn Trì, Minh Khai, Bắc Từ Liêm, Hà Nội</p>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>