Badminton/Controllers/HomeController.cs
using Badminton.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Badminton.Controllers
{
    public class HomeController : Controller
    {
        private BadmintonContext db = new BadmintonContext();

        //Trang chủ admin
        public ActionResult Admin()
        {
            return View();
        }


        //Menu con
        [ChildActionOnly]
        public PartialViewResult SubMenu()
        {
            var query = db.tb_Category.ToList();
            return PartialView(query);
        }
        public ActionResult Index()
        {
            var vot = db.tb_Product.Where(p => p.category_id == 1).OrderBy(p => p.price_new).Take(4).ToList();
            ViewData["Vot"] = vot;

            var giay = db.tb_Product.Where(p => p.category_id == 2).OrderBy(p => p.price_new).Take(4).ToList();
            ViewData["Giay"] = giay;

            return View();
        }
        
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Badminton/Controllers/tb_ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Messaging;
using System.Security;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Badminton.Models;
using Microsoft.Ajax.Utilities;

namespace Badminton.Controllers
{
    public class tb_ProductController : Controller
    {
        private BadmintonContext db = new BadmintonContext();
        
        //Xem toàn bộ sản phẩm

        public ActionResult ShowAllProduct()
        {
            var allProduct = db.tb_Product.ToList();
            return View(allProduct);
        }

        // Tìm kiếm
        public ActionResult Search(string searchString)
        {
            var listSearched  = db.tb_Product.Where(p => p.title.Contains(searchString)).ToList();
            ViewBag.SearchString = searchString;
            return View(listSearched);
        }
        //Kiểm tra sản phẩm có còn trong kho không
        public ActionResult checkSize(string ProductName, string Size)
        {
            tb_Product sp = db.tb_Product.SingleOrDefault(p => p.title == ProductName && p.size == Size);
            if (sp != null)
            {
                var respon = new { status = "yes"};
                return Json(respon, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var respon = new { status = "no"};
                return Json(respon, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult fill(int id, int sort, int cate)
        {
            // Chọn brand rồi mới sắp xếp
            if (id != 0)
            {
                if (sort == 0)
                {
                    return PartialView(db.tb_Product.Where(p => p.brand_id == id && p.category_id == cate).ToList());
                }
                if (sort == 1)
                {
                    return PartialView(db.tb_Product.Where(p => p.brand_id == id && p.category_id == cate).OrderBy(p => p.title).ToList());
                }
                if (sort == 2)
                {
                    return PartialView(db.tb_Product.Where(p => p.brand_id == id && p.category_id == cate).OrderByDescending(p => p.title).ToList());
                }
                if (sort == 3)
                {
                    return PartialView(db.tb_Product.Where(p => p.brand_id == id && p.category_id == cate).OrderBy(p => p.price_new).ToList());
                }
                if (sort == 4)
                {
                    return PartialView(db.tb_Product.Where(p => p.brand_id == id && p.category_id == cate).OrderByDescending(p => p.price_new).ToList());
                }
            }

            // Chưa chọn brand nhưng vẫn muốn sắp xếp
            if (id == 0)
            {
                if (sort == 0)
                {
                    return PartialView(db.tb_Product.Where(p => p.category_id == cate).ToList());
                }
                if (sort == 1)
                {
                    return PartialView(db.tb_Product.Where(p => p.category_id == cate).OrderBy(p => p.title).ToList());
                }
                if (sort == 2)
                {
                    return PartialView(db.tb_Product.Where(p => p.category_id == cate).OrderByDescending(p => p.title).ToList());
                }
                if (sort == 3)
                {
                    return PartialView(db.tb_Product.Where(p => p.category_id == cate).OrderBy(p => p.price_new).ToList());
                }
                if (sort == 4)
                {
                    return PartialView(db.tb_Product.Where(p => p.category_id == cate).OrderByDescending(p => p.price_new).ToList());
                }
            }
            
            return PartialView(db.tb_Product.ToList());
        }

        // GET: Product detail  
        public  ActionResult ProductDetail(int id)
        {
            tb_Product query = db.tb_Product.SingleOrDefault(p => p.id == id);
            return View(query);
        }

        //[Route ("productsByCateID/CateID/{CateID?}")]

        // GET: Product by CateID
        public ActionResult ProductsByCateID(int id)
        {
            string cateName = db.tb_Category.SingleOrDefault(p => p.id == id).categoryname;
            ViewData["cateName"] = cateName;
            ViewData["cateID"] = id;

            var list = db.tb_Product.Where(p => p.category_id == id).ToList();

            return View(list);
        }

        // GET: tb_Product
        public ActionResult Index()
        {
            var tb_Product = db.tb_Product.Include(t => t.tb_Brand).Include(t => t.tb_Category);
            return View(tb_Product.ToList());
        }

        // GET: tb_Product/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Product tb_Product = db.tb_Product.Find(id);
            if (tb_Product == null)
            {
                return HttpNotFound();
            }
            return View(tb_Product);
        }

        // GET: tb_Product/Create
        public ActionResult Create()
        {
            ViewBag.brand_id = new SelectList(db.tb_Brand, "id", "brandname");
            ViewBag.category_id = new SelectList(db.tb_Category, "id", "categoryname");
            return View();
        }

        // POST: tb_Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,title,price,price_new,img,descript,size,stt,category_id,brand_id")] tb_Product tb_Product)
        {
            if (ModelState.IsValid)
            {
                tb_Product.img = "";
                var f = Request.Files["ufile"];
                if (f!=null && f.ContentLength>0)
                {
                    string image = System.IO.Path.GetFileName(f.FileName);
                    tb_Product.img = image;
                    string path = Server.MapPath("/Images/" + image);
                    f.SaveAs(path);
                }
                db.tb_Product.Add(tb_Product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.brand_id = new SelectList(db.tb_Brand, "id", "brandname", tb_Product.brand_id);
            ViewBag.category_id = new SelectList(db.tb_Category, "id", "categoryname", tb_Product.category_id);
            return View(tb_Product);
        }

        // GET: tb_Product/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Product tb_Product = db.tb_Product.Find(id);
            if (tb_Product == null)
            {
                return HttpNotFound();
            }
            ViewBag.brand_id = new SelectList(db.tb_Brand, "id", "brandname", tb_Product.brand_id);
            ViewBag.category_id = new SelectList(db.tb_Category, "id", "categoryname", tb_Product.category_id);
            return View(tb_Product);
        }

        // POST: tb_Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,title,price,price_new,img,descript,size,stt,category_id,brand_id")] tb_Product tb_Product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tb_Product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.brand_id = new SelectList(db.tb_Brand, "id", "brandname", tb_Product.brand_id);
            ViewBag.category_id = new SelectList(db.tb_Category, "id", "categoryname", tb_Product.category_id);
            return View(tb_Product);
        }

        // GET: tb_Product/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tb_Product tb_Product = db.tb_Product.Find(id);
            if (tb_Product == null)
            {
                return HttpNotFound();
            }
            return View(tb_Product);
        }

        // POST: tb_Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tb_Product tb_Product = db.tb_Product.Find(id);
            db.tb_Product.Remove(tb_Product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Badminton/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">Giới thiệu</h2>
    <h3>LINDANSHOP</h3>

    <p>
        Hiện nay, Hệ thống cửa hàng cầu lông LD đã có hơn 50 chi nhánh trải dài trên khắp mọi miền Đất nước. Với tiêu chí luôn đảm bảo cung cấp đầy đủ các mặt hàng chuyên dụng dành riêng cho bộ môn cầu lông như giày, vợt cầu lông, túi vợt, balo, quần áo, phụ kiện,... nổi trội với nhiều phân khúc giá trải dài từ thấp đến cao nên các lông thủ cần mua gì cứ đến ngay với ShopLD, chắc chắn sẽ làm các bạn vô cùng hài lòng.
        <br />
    </p>
    <p>
        ShopLD luôn là nơi cung cấp nhanh nhất các mặt hàng hot đến từ những thương hiệu top đầu thế giới như Yonex, Lining, Victor, Mizuno,... Không những vậy các sản phẩm đến từ các hãng tầm trung và giá rẻ như Adidas, Forza, Apacs, LD, Kamito,... Shop cầu lông LD cũng luôn cung cấp đầy đủ và mẫu mã rất đa dạng.
        <br />
    </p>
    <p>
        * Đặc biệt, ShopLD là địa chỉ nổi tiếng căng vợt cầu lông chuẩn nhất ở Việt Nam. Tất cả các cửa hàng được trang bị máy đan vợt điện tử cao cấp cùng nhân viên ở shop luôn được trau dồi liên tục các kĩ thuật đan vợt hàng đầu trên thế giới.
        <br />
    </p>
    <p class="text-center fw-bold fs-5">TẦM NHÌN, SỨ MỆNH VÀ GIÁ TRỊ CỐT LÕI</p>
    <br />
    <p>
        TẦM NHÌN:  "Trở thành nhà phân phối và sản xuất thể thao lớn nhất Việt Nam"
    </p>
    <p>
        SỨ MỆNH: "LD SPORTS cam kết mang đến những sản phẩm, dịch vụ chất lượng tốt nhất phục vụ cho người chơi thể thao để nâng cao sức khỏe của chính mình."
    </p>
    <p>
        GIÁ TRỊ CỐT LÕI: TRUNG - TÍN - TÂM - TRÍ -NHÂN
    </p>
    <p>
        TRUNG: Trung thực với Khách hàng - Đối tác - Nhân viên. Thực hiện đúng các chế độ ưu đãi, dịch vụ hậu mãi đã cam kết, đặt quyền lợi của người tiêu dùng lên trên hết, chân thành tiếp thu mọi ý kiến đóng góp.
    </p>
    <p>
        TÍN: LD SPORTS đặt chữ TÍN lên hàng đầu, lấy chữ TÍN làm trọng tâm đối với Khách hàng - Đối tác - Nhân viên. LD SPORTS luôn nổ lực hết mình để đảm bảo đúng và cao hơn các cam kết của mình đối với khách hàng, đối tác; đặc biệt là cam kết về chất lượng- sản phẩm - dịch vụ.
    </p>
    <p>
        TÂM: LD SPORTS đặt chữ TÂM là một trong những nền tảng quan trọng của việc kinh doanh. Coi trọng khách hàng và luôn lấy khách hàng làm trung tâm, đặt lợi ích và mong muốn của khách hàng lên hàng đầu; nổ lực mang đến cho khách hàng những sản phẩm - dịch vụ tốt nhất; xem sự hài lòng của khách hàng là thước đo thành công.
    </p>
    <p>
        Trí: LD SPORTS luôn đề cao sự sáng tạo, là đòn bẩy phát triển, nhằm tạo ra giá trị khác biệt và bản sắc riêng của sản phẩm. Chúng tôi đề cao tinh thần dám nghĩ, dám làm, khuyến khích tìm tòi, ứng dụng tiến bộ khoa học, kỹ thuật và công nghệ mới vào quản lý, sản xuất; luôn chủ động cải tiến, nâng cao chất lượng sản phẩm- dịch vụ.
    </p>
    <p>
        NHÂN: LD SPORTS xây dựng các mối quan hệ với khách hàng, đối tác, đồng nghiệp và xã hội bằng sự thiện chí, tinh thần nhân văn. Chúng tôi luôn coi người lao động là tài sản quý giá nhất; xây dựng mội trường làm việc chuyên nghiệp, năng động, sáng tạo; tạo điều kiện thu nhập cao và cơ hội phát triển công bằng cho tất cả cán bộ nhân viên.
    </p>
    <p class="text-danger text-center">
        * ShopLD cam kết bán hàng chính hãng, không bán hàng kém chất lượng làm ảnh hưởng đến thành viên.
    </p>
</main>

Badminton/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">LIÊN HỆ</h2>
    <h3>LIDANSHOP</h3>

    <address>
        Hà Nội<br />
        Minh Khai, Bắc Từ Liêm<br />
        <abbr title="Phone">P: 0967983709</abbr>
        
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">nguyenmanhcuong02062002@gmail.com</a><br />
    </address>
</main>

Badminton/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    List<Badminton.Models.tb_Product> vot = (List<Badminton.Models.tb_Product>)ViewData["Vot"];
    List<Badminton.Models.tb_Product> giay = (List<Badminton.Models.tb_Product>)ViewData["Giay"];
}

<style>
    
    .items > p {
        background-color: #ff0000;
        padding: 10px 20px;
        color: white;
        width: 200px;
        text-align: center;
        position: absolute;
        
    }
    .items {
        text-decoration: none;
        position: relative;
        display: flex;
        align-items: center;
        justify-content: center;
        margin-top: 30px;
    }
    .items img {
        max-width: 340px;
    }
    .items:hover {
        opacity: 50%;
    }
    td a{
        text-decoration: none;
        color: black;   
    }
    td a:hover {
        opacity: 70%;
    }
</style>

<main>
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Images/slide5.jpg" class="d-block" width="1200" height="800" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Images/slide2.jpeg" class="d-block" width="1200" height="800" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Images/slide4.jpg" class="d-block" width="1200" height="800" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Images/slide1.jpg" class="d-block" width="1200" height="800" alt="...">
            </div>
        </div>
    </div>

    <div class="container">
        <h1 class="text-center text-danger m-5">Sản phẩm HOT</h1>
        <div id="carouselExample" class="carousel slide">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <table align="center">
                        <tr>
                            @foreach (var item in vot)
                            {
                                <td class="">
                                    <a href="/tb_Product/ProductDetail/@item.id">
                                        <div class="card" style="width: 250px; height: 400px;">
                                            <img class="card-img-top" src="~/Images/@item.img" style="height: 250px;"/>
                                            <div class="card-body">
                                                <p style="height: 40px;">@item.title</p>
                                                <p>@item.price_new đ</p>
                                            </div>
                                        </div>
                                    </a>
                                   
                                </td>
                            }
                        </tr>
                    </table>
                </div>
                <div class="carousel-item">
                    <table align="center">
                        <tr>
                            @foreach (var item in giay)
                            {
                                <td>
                                    <a href="/tb_Product/ProductDetail/@item.id">
                                        <div class="card" style="width: 250px; height: 400px;">
                                            <img class="card-img-top" src="~/Images/@item.img" style="height: 250px;"/>
                                            <div class="card-body">
                                                <p style="height: 40px;">@item.title</p>
                                                <p>@item.price_new đ</p>
                                            </div>
                                        </div>
                                    </a>
                                   
                                </td>
                            }
                        </tr>
                    </table>
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon text-bg-secondary" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon text-bg-secondary" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>


    <div class="container ">
        <h1 class="text-center text-danger m-5">Sản phẩm cầu lông</h1>
        <div class="row">
            <a href="/tb_Product/ProductsByCateID/1" class="items col">
                <img src="~/Images/vot.png">
                <p class="title">Vợt cầu lông</p>
            </a>
            <a href="/tb_Product/ProductsByCateID/2" class="items col">
                <img src="~/Images/giay.png">
                <p class="title">Giày cầu lông</p>
            </a>
            <a href="/tb_Product/ProductsByCateID/3" class="items col">
                <img src="~/Images/ao.png">
                <p class="title">Quần áo cầu lông</p>
            </a>
            <a href="/tb_Product/ProductsByCateID/4" class="items col">
                <img src="~/Images/balo.png">
                <p class="title">Ba lô cầu lông</p>
            </a>
            <a href="/tb_Product/ProductsByCateID/5" class="items col">
                <img src="~/Images/tui.png">
                <p class="title">Túi cầu lông</p>
            </a>
            <a href="/tb_Product/ProductsByCateID/6" class="items col">
                <img src="~/Images/phukien.png">
                <p class="title">Phụ kiện cầu lông</p>
            </a>
        </div>
    </div>
</main>

Badminton/Views/Home/SubMenu.cshtml
@model IEnumerable<Badminton.Models.tb_Category>

@{
    foreach (var item in Model)
    {
        var url = "productsByCateID/CateID/" + item.id;
        <li>
            @Html.ActionLink(item.categoryname, "ProductsByCateID", "tb_Product", new { id = item.id}, new {@class = "nav-link"})
        </li>

    }
}